[tools]
claude = "latest"
codex = "latest"
gemini = { version = "latest", allow_builds = ["@github/keytar", "node-pty"] }
gh = "latest"
node = "latest"
opencode = "latest"
pi = "latest"
pnpm = "9"
shfmt = "3.13.1"
typst = "0.14.2"
uv = "latest"

[settings.upgrade]
auto_prune = false
